"""add provider assignment to breakdown

Revision ID: d16eff2dd1cf
Revises: 706788864ff6
Create Date: 2026-09-12 20:09:06.985914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16eff2dd1cf'
down_revision: Union[str, Sequence[str], None] = '706788864ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breakdown_requests', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_breakdown_requests_provider_id'), 'breakdown_requests', ['provider_id'], unique=False)
    op.create_foreign_key(None, 'breakdown_requests', 'providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'breakdown_requests', type_='foreignkey')
    op.drop_index(op.f('ix_breakdown_requests_provider_id'), table_name='breakdown_requests')
    op.drop_column('breakdown_requests', 'provider_id')
    # ### end Alembic commands ###
